# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure("2") do |config|
    
    
    config.vm.define "master" do |master|
            master.vm.hostname = "master"
            master.vm.box = "bento/ubuntu-18.04"
            master.vm.network 'private_network', ip: "172.100.100.1"
            master.vm.provider 'virtualbox' do |vb|
                vb.name = "master"
                vb.memory = 2048
                vb.cpus = 2
            end
        end

    NodeCount =  2
    
    (1..NodeCount).each do |i|
        config.vm.define "worker#{i}" do |node|
            node.vm.hostname = "worker#{i}"
            node.vm.box = "bento/ubuntu-18.04"
            node.vm.network 'private_network', ip: "172.100.100.#{1+i}"
            node.vm.provider 'virtualbox' do |vb|
                vb.name = "worker#{i}"
                vb.memory = 1024
                vb.cpus = 1
            end
        end
    end
end




